### PR TITLE
Add exports test

### PR DESCRIPTION
**Pull request by david-yan**

### CODE REVIEW

**Comment by nhynes** [comment]
What's the purpose of this test exactly?

**Comment by david-yan** [comment]
Just to test that I can call something other than `call`. In this case, an export called `func`.

**Comment by nhynes** [comment]
is there a corresponding test in ethcore? I'm not sure that this actually needs to be merged since we already know that any export is callable.

**Comment by david-yan** [comment]
Corresponding test exists in https://github.com/oasislabs/parity/pull/105

**Pull request closed without merging**
